services:
  proeventosapp:
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --openssl-legacy-provider
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
